"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

ZITADEL_SERVER_URL = os.environ["ZITADEL_SERVER_URL"]
ZITADEL_CLIENT_ID = os.environ["ZITADEL_CLIENT_ID"]
ZITADEL_CLIENT_SECRET = os.environ["ZITADEL_CLIENT_SECRET"]

OIDC_OP_LOGOUT_ENDPOINT = f"{ZITADEL_SERVER_URL}/oidc/v1/end_session"
OIDC_RP_POST_LOGOUT_REDIRECT_URI = "http://localhost:8000/"

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "corsheaders",
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "mozilla_django_oidc.middleware.SessionRefresh",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
]

CORS_ALLOWED_ORIGINS = ["http://localhost:8081"]
ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "pokemon",
        "USER": "root",
        "PASSWORD": "root",
        "PORT": "3306",
        "HOST": "127.0.0.1",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Mozilla Django OIDC Configuration for Zitadel
OIDC_RP_CLIENT_ID = ZITADEL_CLIENT_ID
OIDC_RP_CLIENT_SECRET = ZITADEL_CLIENT_SECRET
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{ZITADEL_SERVER_URL}/oauth/v2/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{ZITADEL_SERVER_URL}/oauth/v2/token"
OIDC_OP_USER_ENDPOINT = f"{ZITADEL_SERVER_URL}/oidc/v1/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"{ZITADEL_SERVER_URL}/oauth/v2/keys"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid profile email"


  # Exempt API endpoints from OIDC session middleware
  # This allows API endpoints to use JWT authentication instead

OIDC_EXEMPT_URLS = [
    r'^/api/',
    r'^/api/',
    r'^/health/',
]

# Redirect URIs
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/oidc/authenticate/"
OIDC_CALLBACK_CLASS = "mozilla_django_oidc.views.OIDCAuthenticationCallbackView"

# IMPORTANT: This is the redirect_uri sent to Zitadel
# Must match what's configured in Zitadel application settings
OIDC_RP_CALLBACK_URI = "http://localhost:8000/oidc/callback/"

# Optional: Create users automatically
OIDC_CREATE_USER = True
OIDC_UPDATE_USER = True
