# Generated by Django 5.2.6 on 2025-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('card_id', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50, null=True)),
                ('rarity', models.CharField(max_length=50, null=True)),
                ('illustrator', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Common', 'Common'), ('Unusual', 'Unusual'), ('Rare', 'Rare'), ('Ultra Rare', 'Ultra Rare'), ('Ex', 'Ex'), ('X', 'X'), ('Full Art', 'Full Art'), ('Shiny Gold', 'Shiny Gold')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
