# Generated by Django 5.2.6 on 2025-10-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pokemon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("card_id", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Rarity_Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Common", "Common"),
                            ("Unusual", "Unusual"),
                            ("Rare", "Rare"),
                            ("Ultra Rare", "Ultra Rare"),
                            ("Ex", "Ex"),
                            ("X", "X"),
                            ("Full Art", "Full Art"),
                            ("Shiny Gold", "Shiny Gold"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
    ]
