# Generated by Django 5.2.6 on 2025-12-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_user',
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.card')),
                ('card_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to='app.user')),
            ],
        ),
    ]
