# Generated by Django 5.2.6 on 2025-10-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
