# Generated by Django 5.2.6 on 2025-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pokemon_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, to='app.user'),
        ),
    ]
