# Generated by Django 6.0.3 on 2026-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_booster_opened',
            field=models.DateField(blank=True, null=True),
        ),
    ]
