# Generated by Django 6.0.3 on 2026-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_last_booster_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booster_count',
            field=models.IntegerField(default=0),
        ),
    ]
