# Generated by Django 6.0.3 on 2026-04-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_last_booster_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
