# Generated by Django 6.0.3 on 2026-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_booster_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='booster_count',
            field=models.IntegerField(default=0),
        ),
    ]
