# Generated by Django 6.0.3 on 2026-04-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_card_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='type',
            new_name='types',
        ),
    ]
