# Generated by Django 6.0.3 on 2026-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_card_booster_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='booster_count',
        ),
    ]
