# Generated by Django 6.0.3 on 2026-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_type_card_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('symbol', models.URLField(blank=True, null=True)),
                ('card_count_total', models.IntegerField(default=0)),
                ('card_count_official', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolution',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolve_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
