# Generated by Django 6.0.3 on 2026-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cardset_card_description_card_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='evolve_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='symbol',
            field=models.URLField(null=True),
        ),
    ]
