# Generated by Django 6.0.3 on 2026-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_card_booster_count'),
        ('app', '0011_alter_card_description_alter_card_evolve_from_and_more'),
    ]

    operations = [
    ]
