# Generated by Django 6.0.3 on 2026-04-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20260407_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
