# Generated by Django 6.0.3 on 2026-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20260407_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
