# Generated by Django 6.0.3 on 2026-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
