# Generated by Django 6.0.3 on 2026-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_card_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.IntegerField(null=True),
        ),
    ]
