# Generated by Django 6.0.3 on 2026-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_playercard_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='Kanto', max_length=50),
        ),
    ]
