# Generated by Django 5.2.6 on 2026-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_booster_count',
            field=models.IntegerField(default=0),
        ),
    ]
