# Write a default echo test on pr open and changes

name: PR Opened
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Opened
        run: echo "Pull Request"
      - name: Echo PR Changes
        run: echo "Pull Request changes"
